steps:
  # Get secrets from Secret Manager and write to env file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=web-env-production > /workspace/app-web/.env.production
  
  # Build the Docker image with build args from env file
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Source environment variables from Secret Manager
        set -a
        source /workspace/app-web/.env.production
        set +a
        
        # Build with environment variables as build args
        docker build \
          -t gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest \
          --build-arg NEXT_PUBLIC_SUPABASE_URL="$${NEXT_PUBLIC_SUPABASE_URL}" \
          --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="$${NEXT_PUBLIC_SUPABASE_ANON_KEY}" \
          --build-arg NEXT_PUBLIC_SITE_URL="$${NEXT_PUBLIC_SITE_URL}" \
          --build-arg API_URL="$${API_URL}" \
          -f ./app-web/Dockerfile \
          ./app-web

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

  # Deploy to Cloud Run with environment variables from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get environment variables from Secret Manager
        gcloud secrets versions access latest --secret=web-env-production > /tmp/env.tmp
        
        # Source the environment variables
        set -a
        source /tmp/env.tmp
        set +a
        
        # Deploy with environment variables
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --service-account web-sa@${PROJECT_ID}.iam.gserviceaccount.com \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --concurrency 80 \
          --set-env-vars "NEXT_PUBLIC_SUPABASE_URL=$${NEXT_PUBLIC_SUPABASE_URL}" \
          --set-env-vars "NEXT_PUBLIC_SUPABASE_ANON_KEY=$${NEXT_PUBLIC_SUPABASE_ANON_KEY}" \
          --set-env-vars "NEXT_PUBLIC_SITE_URL=$${NEXT_PUBLIC_SITE_URL}" \
          --set-env-vars "API_URL=$${API_URL}"

substitutions:
  _SERVICE_NAME: 'web-app-web'
  _REGION: 'asia-northeast1'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

timeout: '1200s'

# Cloud Build options
options:
  logging: CLOUD_LOGGING_ONLY
