options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _STACK: prod  # 本番環境のみ使用
  _REGION: asia-northeast1

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/PULUMI_ACCESS_TOKEN/versions/latest
      env: "PULUMI_ACCESS_TOKEN"

steps:
  - name: gcr.io/cloud-builders/npm
    dir: infra/pulumi
    args: ["ci"]

  - name: "pulumi/pulumi-nodejs"
    dir: infra/pulumi
    entrypoint: bash
    env:
      - "PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN}"
    args:
      - -lc
      - |
        pulumi stack select ${_STACK} || pulumi stack init ${_STACK}
        pulumi config set project $PROJECT_ID
        pulumi config set region ${_REGION}
        pulumi up --yes