// エラーコードのマッピングを as const で定義
export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN_OPERATION: 'FORBIDDEN_OPERATION',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_TYPE: 'INVALID_TYPE',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  CONFLICT: 'CONFLICT',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  TIMEOUT: 'TIMEOUT',
  BAD_REQUEST: 'BAD_REQUEST',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const

// typeof ERROR_CODES からキーの型を抜き出す
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
