// src/utils/error/error-code.ts

// エラーコードのマッピングを as const で定義
export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN_OPERATION: "FORBIDDEN_OPERATION",
  NOT_FOUND: "NOT_FOUND",
  INVALID_TOKEN: "INVALID_TOKEN",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  AGE_VERIFICATION_FAILED: "AGE_VERIFICATION_FAILED",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  SEND_NOTIFICATION_FAILED: "SEND_NOTIFICATION_FAILED",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  INVALID_TYPE: "INVALID_TYPE",
  INVALID_REQUEST: "INVALID_REQUEST",

  // ユーザープロフィール関連
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // Google Place API関連
  INVALID_PLACE_ID: "INVALID_PLACE_ID",
  PLACE_NOT_FOUND: "PLACE_NOT_FOUND",
  PLACE_DETAILS_ERROR: "PLACE_DETAILS_ERROR",
  GOOGLE_CLOUD_PROJECT_ID_NOT_FOUND: "GOOGLE_CLOUD_PROJECT_ID_NOT_FOUND",

  // 友達関係関連
  FRIENDSHIP_NOT_FOUND: "FRIENDSHIP_NOT_FOUND",
  FRIENDSHIP_ALREADY_EXISTS: "FRIENDSHIP_ALREADY_EXISTS",
  FRIENDSHIP_REQUEST_NOT_FOUND: "FRIENDSHIP_REQUEST_NOT_FOUND",
  FRIENDSHIP_REQUEST_ALREADY_ACCEPTED: "FRIENDSHIP_REQUEST_ALREADY_ACCEPTED",
  FRIENDSHIP_REQUEST_ALREADY_REJECTED: "FRIENDSHIP_REQUEST_ALREADY_REJECTED",
  FRIENDSHIP_REQUEST_ALREADY_EXISTS: "FRIENDSHIP_REQUEST_ALREADY_EXISTS",
  FRIENDSHIP_ONLY_HOMOSEXUAL: "FRIENDSHIP_ONLY_HOMOSEXUAL",

  // 募集
  POST_NOT_FOUND: "POST_NOT_FOUND",

  // 合流リクエスト関連
  JOIN_REQUEST_NOT_FOUND: "JOIN_REQUEST_NOT_FOUND",

  // 保存済み検索条件関連
  SAVED_SEARCH_NOT_FOUND: "SAVED_SEARCH_NOT_FOUND",

  // 今夜の参加グループ関連
  TONIGHT_PARTICIPATION_GROUP_NOT_FOUND:
    "TONIGHT_PARTICIPATION_GROUP_NOT_FOUND",

  // チャットルーム関連
  CHAT_ROOM_NOT_FOUND: "CHAT_ROOM_NOT_FOUND",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
} as const;

// typeof ERROR_CODES からキーの型を抜き出す
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
