# Google Cloud Build configuration for API
steps:
  # Install dependencies
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'api'

  # Build TypeScript
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'api'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api:latest'
      - '-f'
      - 'api/Dockerfile'
      - './api'

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/api'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api:$SHORT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - '/workspace/.env=api-env-production:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'