steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web-app-api:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web-app-api:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/web-app-api'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'web-app-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/web-app-api:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - '/etc/secrets/.env=api-env-production:latest'

images:
  - 'gcr.io/$PROJECT_ID/web-app-api:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/web-app-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY